# Generated by Django 2.0.6 on 2018-10-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='disiplinaOfertada',
            field=models.IntegerField(null=True),
        ),
    ]
